apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-website
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: razzkumar/ex-api:latest
        ports:
        - containerPort: 3000
