apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        # image: razzkumar/ex-api:latest
        image: registry.digitalocean.com/exp-app/app:v0.0.1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registry-exp-app
